// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbM1Oba9Qy6pvjjHdQff1RFi9BOMSe_KE',
    appId: '1:202293837472:web:f40a23b7dcc78bfa5a93c5',
    messagingSenderId: '202293837472',
    projectId: 'racharuchi-02',
    authDomain: 'racharuchi-02.firebaseapp.com',
    storageBucket: 'racharuchi-02.firebasestorage.app',
    measurementId: 'G-CTZVVVNBFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_QLNQ75MddPpj-lwTGmpJd797lNj1xBQ',
    appId: '1:202293837472:android:d0259f4c4bab24695a93c5',
    messagingSenderId: '202293837472',
    projectId: 'racharuchi-02',
    storageBucket: 'racharuchi-02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjb_vsWkABxcfd_gUl3RJTnmKFqFLIcpU',
    appId: '1:202293837472:ios:0c21fada22d464905a93c5',
    messagingSenderId: '202293837472',
    projectId: 'racharuchi-02',
    storageBucket: 'racharuchi-02.firebasestorage.app',
    iosClientId: '202293837472-6a0ek70brolnrjk04i5v28l83s6s628q.apps.googleusercontent.com',
    iosBundleId: 'com.example.racharuchi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjb_vsWkABxcfd_gUl3RJTnmKFqFLIcpU',
    appId: '1:202293837472:ios:0c21fada22d464905a93c5',
    messagingSenderId: '202293837472',
    projectId: 'racharuchi-02',
    storageBucket: 'racharuchi-02.firebasestorage.app',
    iosClientId: '202293837472-6a0ek70brolnrjk04i5v28l83s6s628q.apps.googleusercontent.com',
    iosBundleId: 'com.example.racharuchi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbM1Oba9Qy6pvjjHdQff1RFi9BOMSe_KE',
    appId: '1:202293837472:web:16935ef7775f55a85a93c5',
    messagingSenderId: '202293837472',
    projectId: 'racharuchi-02',
    authDomain: 'racharuchi-02.firebaseapp.com',
    storageBucket: 'racharuchi-02.firebasestorage.app',
    measurementId: 'G-ZL7B3B4JX2',
  );

}